# -*- coding: utf-8 -*-
"""GeoTiff->csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18hCch3_OO2A3gHO8NQJhYJpLQRWiQhUH
"""

!pip install rasterio pandas

from google.colab import files
uploaded = files.upload()

import rasterio
import pandas as pd
import numpy as np

# Users can replace with 'user_file_name.tif'
tiff_file = 'ForestLoss_NewAOI (2).tif'

# Open the TIFF file
with rasterio.open(tiff_file) as src:
    data = src.read(1) 
    transform = src.transform  
    nodata = src.nodata  

    # Get the dimensions of the raster
    rows, cols = data.shape

    # Create an array of row and column indices
    row_indices, col_indices = np.indices((rows, cols))

    # Convert row and column indices to geographic coordinates
    x_coords, y_coords = rasterio.transform.xy(transform, row_indices, col_indices)

    # Flatten the arrays
    x_coords_flat = np.array(x_coords).flatten()
    y_coords_flat = np.array(y_coords).flatten()
    values_flat = data.flatten()

    # Create a DataFrame
    df = pd.DataFrame({
        'Longitude': x_coords_flat,
        'Latitude': y_coords_flat,
        'Value': values_flat
    })

    # Save the DataFrame to CSV
    csv_file = 'output_file.csv'
    df.to_csv(csv_file, index=False)
    print(f'CSV file saved as {csv_file}')

from google.colab import files
files.download('output_file.csv')
